#!/bin/bash

# Copyright 2020 Wazo Communication inc.
# SPDX-License-Identifier: GPL-3.0-or-later

# Supported environments:
# - EUC Stack 20.12
# - EUC Stack installed from ISO
# - EUC Stack installed script
# - EUC Stack, wizard configured
# - EUC Stack, wizard not configured
# - Wazo Platform 20.12
# - Wazo Platform freshly installed, wizard not configured
# - Wazo Platform, wizard configured without Nestbox
# - Wazo Platform, wizard configured with Nestbox
# - Wazo Platform upgraded from Wazo < 16.13

# Unsupported environments:
# - Wazo Platform not installed

set -e

echo "Getting Wazo version..."
EUC_VERSION=$(cat /usr/share/wazo/WAZO-VERSION)

if [[ "$EUC_VERSION" != ??.?? ]] ; then
    echo "Error code 05: invalid Wazo version '$EUC_VERSION'"
    exit 5
fi
if [[ "$EUC_VERSION" < "20.11" ]] ; then
    EUC_VERSION=20.11
fi

echo "Adding Wazo EUC Stack repository..."
apt-get update -qq
apt-get install -yqq ca-certificates

cat > /etc/apt/sources.list.d/wazo-enterprise.list <<EOF
deb https://mirror.wazo.io/enterprise-archive enterprise-$EUC_VERSION main
EOF
rm -f /etc/apt/sources.list.d/wazo-dist.list /etc/apt/sources.list.d/xivo-dist.list

apt-get update -qq

echo "Verifying repositories..."
if apt-cache policy | grep -qE "http://mirror.wazo.community/debian (wazo-dev|wazo-rc|pelican)-buster" ; then
    echo "Error code 02: Wazo Platform configuration is still present."
    echo "Please send this error and the output of 'apt-cache policy' to Wazo Support."
    exit 2
fi
if ! apt-cache policy | grep -qE "https://mirror.wazo.io/enterprise-archive enterprise-$EUC_VERSION" ; then
    echo "Error code 03: Wazo EUC Stack configuration not found."
    echo "Please send this error and the output of 'apt-cache policy' and 'apt-get update' to Wazo Support."
    exit 3
fi

echo "Installing Wazo EUC Stack packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get install -yqq wazo-enterprise wazo-plugind-cli
if [[ "$EUC_VERSION" < "21.02" ]] ; then
    apt-get install -yqq wazo-nestbox-plugin wazo-deployd-client
fi

echo "Restarting wazo-auth..."
systemctl restart wazo-auth

echo "Updating Wazo EUC Stack repository..."
cat > /etc/apt/sources.list.d/wazo-enterprise.list <<EOF
deb https://mirror.wazo.io/enterprise enterprise-buster main
EOF

apt-get update -qq

if ! apt-cache policy | grep -qE "https://mirror.wazo.io/enterprise enterprise-(dev-|rc-|)buster" ; then
    echo "Error code 06: Wazo EUC Stack updated configuration not found."
    echo "Please send this error and the output of 'apt-cache policy' and 'apt-get update' to Wazo Support."
    exit 6
fi

: ${WAZO_CONFD_PORT:='9486'}
is_wazo_configured() {
    if ! systemctl is-active --quiet wazo-confd; then
        echo "Error code 04: wazo-confd is not running: cannot check if the web wizard has been run."
        exit 4
    fi
    # wazo-confd has no HTTPS since wazo-20.07
    for scheme in 'http' 'https'; do
        if [ -n "$(curl -skX GET --header 'Accept: application/json' "$scheme://localhost:$WAZO_CONFD_PORT/1.1/wizard" | grep '\"configured\"[[:space:]]*:[[:space:]]*true')" ]; then
            return
        fi
    done
    return 1
}

wazo_nestbox_plugin_configured() {
    test -s /usr/share/wazo-setupd/50-wazo-plugin-nestbox.yml
}

if is_wazo_configured ; then
    echo "Validating connection to Portal..."
    if ! wazo_nestbox_plugin_configured ; then
        echo "Error code 01: Wazo Portal configuration not found."
        echo "Please send this error to Wazo Support."
        exit 1
    fi
fi

echo "Migration to Wazo EUC Stack finished."

remove_euc_stack_migration() {
    wazo-plugind-cli -c "uninstall official/wazo-euc-stack-migration --async"
}

prompt_remove_migration_plugin() {
    while true; do
        read -p "Do you want to remove the migration plugin? ([Y]/n) " yn
        case $yn in
            ""|[Yy]* ) WAZO_REMOVE_EUC_STACK_MIGRATION_PLUGIN=1; break;;
            [Nn]* ) WAZO_REMOVE_EUC_STACK_MIGRATION_PLUGIN=0; break;;
            * ) echo "Please answer yes or no.";;
        esac
    done
}

if [ -z "$WAZO_REMOVE_EUC_STACK_MIGRATION_PLUGIN" ] ; then
    prompt_remove_migration_plugin
fi

if [ "$WAZO_REMOVE_EUC_STACK_MIGRATION_PLUGIN" -eq 1 ] ; then
    echo "Removing the migration plugin..."
    remove_euc_stack_migration
fi

echo "Migration to Wazo EUC Stack successful."

